// <auto-generated />
using System;
using Fina.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fina.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fina.Core.Models.Banco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("nome");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_banco");

                    b.ToTable("banco", (string)null);
                });

            modelBuilder.Entity("Fina.Core.Models.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Color")
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("color");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("descricao");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("icon");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("nome");

                    b.Property<int>("TipoCategoria")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_categoria");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_categoria");

                    b.ToTable("categoria", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d2afc928-38e8-4d8b-8c40-000000000001"),
                            Ativo = true,
                            Color = "#4CAF50",
                            CriadaEm = new DateTime(2025, 1, 1, 3, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Recebimento de salário",
                            Icon = "wallet",
                            IsDefault = true,
                            Nome = "Salário",
                            TipoCategoria = 1,
                            UsuarioId = ""
                        },
                        new
                        {
                            Id = new Guid("d2afc928-38e8-4d8b-8c40-000000000002"),
                            Ativo = true,
                            Color = "#2E7D32",
                            CriadaEm = new DateTime(2025, 1, 1, 3, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Trabalhos extras",
                            Icon = "briefcase",
                            IsDefault = true,
                            Nome = "Freelance",
                            TipoCategoria = 1,
                            UsuarioId = ""
                        },
                        new
                        {
                            Id = new Guid("d2afc928-38e8-4d8b-8c40-000000000003"),
                            Ativo = true,
                            Color = "#388E3C",
                            CriadaEm = new DateTime(2025, 1, 1, 3, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Rendimentos de investimentos",
                            Icon = "trending_up",
                            IsDefault = true,
                            Nome = "Investimentos",
                            TipoCategoria = 1,
                            UsuarioId = ""
                        },
                        new
                        {
                            Id = new Guid("d2afc928-38e8-4d8b-8c40-000000000101"),
                            Ativo = true,
                            Color = "#F44336",
                            CriadaEm = new DateTime(2025, 1, 1, 3, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Aluguel, condomínio, IPTU",
                            Icon = "home",
                            IsDefault = true,
                            Nome = "Moradia",
                            TipoCategoria = 2,
                            UsuarioId = ""
                        },
                        new
                        {
                            Id = new Guid("d2afc928-38e8-4d8b-8c40-000000000102"),
                            Ativo = true,
                            Color = "#FF9800",
                            CriadaEm = new DateTime(2025, 1, 1, 3, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Mercado e restaurantes",
                            Icon = "restaurant",
                            IsDefault = true,
                            Nome = "Alimentação",
                            TipoCategoria = 2,
                            UsuarioId = ""
                        },
                        new
                        {
                            Id = new Guid("d2afc928-38e8-4d8b-8c40-000000000103"),
                            Ativo = true,
                            Color = "#2196F3",
                            CriadaEm = new DateTime(2025, 1, 1, 3, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Combustível, ônibus, Uber",
                            Icon = "directions_car",
                            IsDefault = true,
                            Nome = "Transporte",
                            TipoCategoria = 2,
                            UsuarioId = ""
                        },
                        new
                        {
                            Id = new Guid("d2afc928-38e8-4d8b-8c40-000000000104"),
                            Ativo = true,
                            Color = "#E91E63",
                            CriadaEm = new DateTime(2025, 1, 1, 3, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Plano de saúde, consultas e medicamentos",
                            Icon = "favorite",
                            IsDefault = true,
                            Nome = "Saúde",
                            TipoCategoria = 2,
                            UsuarioId = ""
                        },
                        new
                        {
                            Id = new Guid("d2afc928-38e8-4d8b-8c40-000000000105"),
                            Ativo = true,
                            Color = "#3F51B5",
                            CriadaEm = new DateTime(2025, 1, 1, 3, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Cursos e mensalidades",
                            Icon = "school",
                            IsDefault = true,
                            Nome = "Educação",
                            TipoCategoria = 2,
                            UsuarioId = ""
                        },
                        new
                        {
                            Id = new Guid("d2afc928-38e8-4d8b-8c40-000000000106"),
                            Ativo = true,
                            Color = "#9C27B0",
                            CriadaEm = new DateTime(2025, 1, 1, 3, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Cinema, viagens e entretenimento",
                            Icon = "sports_esports",
                            IsDefault = true,
                            Nome = "Lazer",
                            TipoCategoria = 2,
                            UsuarioId = ""
                        },
                        new
                        {
                            Id = new Guid("d2afc928-38e8-4d8b-8c40-000000000107"),
                            Ativo = true,
                            Color = "#795548",
                            CriadaEm = new DateTime(2025, 1, 1, 3, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Roupas e compras em geral",
                            Icon = "shopping_cart",
                            IsDefault = true,
                            Nome = "Compras",
                            TipoCategoria = 2,
                            UsuarioId = ""
                        },
                        new
                        {
                            Id = new Guid("d2afc928-38e8-4d8b-8c40-000000000108"),
                            Ativo = true,
                            Color = "#607D8B",
                            CriadaEm = new DateTime(2025, 1, 1, 3, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Netflix, Spotify e outros serviços",
                            Icon = "subscriptions",
                            IsDefault = true,
                            Nome = "Assinaturas",
                            TipoCategoria = 2,
                            UsuarioId = ""
                        },
                        new
                        {
                            Id = new Guid("d2afc928-38e8-4d8b-8c40-000000000109"),
                            Ativo = true,
                            Color = "#B71C1C",
                            CriadaEm = new DateTime(2025, 1, 1, 3, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Tributos e taxas",
                            Icon = "receipt_long",
                            IsDefault = true,
                            Nome = "Impostos",
                            TipoCategoria = 2,
                            UsuarioId = ""
                        },
                        new
                        {
                            Id = new Guid("d2afc928-38e8-4d8b-8c40-000000000110"),
                            Ativo = true,
                            Color = "#757575",
                            CriadaEm = new DateTime(2025, 1, 1, 3, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Outras despesas",
                            Icon = "Categoria",
                            IsDefault = true,
                            Nome = "Outros",
                            TipoCategoria = 2,
                            UsuarioId = ""
                        },
                        new
                        {
                            Id = new Guid("d2afc928-38e8-4d8b-8c40-000000000111"),
                            Ativo = true,
                            Color = "#757575",
                            CriadaEm = new DateTime(2025, 1, 1, 3, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Despesas com Pet",
                            Icon = "Categoria",
                            IsDefault = true,
                            Nome = "Pet",
                            TipoCategoria = 2,
                            UsuarioId = ""
                        });
                });

            modelBuilder.Entity("Fina.Core.Models.SubCategoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("nome");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_sub_categoria");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_sub_categoria_categoria_id");

                    b.ToTable("sub-categoria", (string)null);
                });

            modelBuilder.Entity("Fina.Core.Models.Transacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnName("descricao");

                    b.Property<string>("FormaPagamentoRecebimento")
                        .HasColumnType("VARCHAR")
                        .HasColumnName("forma_pagamento_recebimento");

                    b.Property<string>("OrigemPagamentoRecebimento")
                        .HasColumnType("VARCHAR")
                        .HasColumnName("origem_pagamento_recebimento");

                    b.Property<DateTime?>("PagoRecebidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pago_recebido_em");

                    b.Property<string>("StatusTransacao")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnName("status_transacao");

                    b.Property<Guid?>("SubCategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("subcategoria_id");

                    b.Property<string>("TipoTransacao")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnName("tipo_transacao");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("titulo");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("Valor")
                        .HasColumnType("MONEY")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_transacao");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_transacao_categoria_id");

                    b.HasIndex("SubCategoriaId")
                        .HasDatabaseName("ix_transacao_sub_categoria_id");

                    b.ToTable("transacao", (string)null);
                });

            modelBuilder.Entity("Fina.Core.Models.SubCategoria", b =>
                {
                    b.HasOne("Fina.Core.Models.Categoria", "Categoria")
                        .WithMany("SubCategorias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subcategorias_categorias_categoria_id");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Fina.Core.Models.Transacao", b =>
                {
                    b.HasOne("Fina.Core.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transacao_categoria_categoria_id");

                    b.HasOne("Fina.Core.Models.SubCategoria", "SubCategoria")
                        .WithMany()
                        .HasForeignKey("SubCategoriaId")
                        .HasConstraintName("fk_transacao_sub_categoria_sub_categoria_id");

                    b.Navigation("Categoria");

                    b.Navigation("SubCategoria");
                });

            modelBuilder.Entity("Fina.Core.Models.Categoria", b =>
                {
                    b.Navigation("SubCategorias");
                });
#pragma warning restore 612, 618
        }
    }
}
